### ISSUE TITLE
Apple watch notification delay

### ISSUE THREAD

**Issue by wynnb0677** [kpwn/yalu102#115]
After running Yalu102 the jailbreak seems to delay the connection between phone and watch, as notifications are delayed, and unable to send apps to watch. 
From other accounts: 
Do Not Disturb mirroring appears to be broken
Unable to send apps to watch
Notification delayed

Only fix so far seems to be repairing watch after running Yalu102. But this doesn't seem like a permanent fix as you have to do this every time you run Yalu102.

**Comment by kpwn** [comment]
hmm, i wonder if this is due to how I reload userland.

**Comment by keldegar** [comment]
I am also having this issue. Delayed notifications, cannot install apps. DND mirror does not work.

**Comment by tomlube** [comment]
@kpwn probably not. This is a known issue with Apple Watch and hard reboots. I had to restore and re-sync my Apple Watch after taking my iPhone 6 completely apart. Issue is resolved permanently by re syncing.

**Comment by keldegar** [comment]
@tomlube just tested... did a normal shutdown. Start up, re-run Yalu102. Watch broken again. 

Cannot DND, cannot install apps.

**Comment by simsdj** [comment]
I also have this issue

**Comment by keldegar** [comment]
@simsdj yeah I also noticed when it's broken, you get double notifications on phone and watch, when phone is asleep.

**Comment by simsdj** [comment]
@keldegar i was hoping someone would've already posted about their apple watch. glad to know I'm not the only one.

**Comment by wynnb0677** [comment]
@tomlube people have stated that it breaks whenever they run Yalu. I wouldn't call re-syncing every time you reboot a permanent fix.

**Comment by calabreee** [comment]
I'm experiencing this as well, watch is out of sync and notifications are delayed about 20-30 seconds

**Comment by cyanisaac** [comment]
Can confirm everything in this thread happens to me as well, even with tweaks disabled.

**Comment by MacKeeper28** [comment]
Can confirm all of the above, I've gotten notifications to work temporarily by messing around with airplane mode on both the phone and watch.  iPhone 6s iOS 10.2, Apple Watch Series 2 watchOS 3.1

**Comment by xXDjMikeXx** [comment]
I had this problem after downgrading from 10.2 to 10.1.1 but this bug went away from its self

**Comment by cyanisaac** [comment]
For me, the issues go away when Yalu102 is not active. Even when the Watch is paired while Yalu is running (which others report makes it work), rebooting and running iOS without the jailbreak doesn't cause any issues for the Watch. The issues return when the jailbreak is activated.

**Comment by justinoboyle** [comment]
Would like to note that on the new early 4K support, iPhone 6, everything appears to be acting normally with the watch notifications. Maybe I'm an edge case? Anyway, just wanted to put the information down

**Comment by keldegar** [comment]
@justinoboyle notifications work but are delayed slightly and also appear on the phone. are you able to turn on DND mirrored, or install any apps onto the watch in jailbreak state? you didn't re-pair your watch?

**Comment by doio** [comment]
I am having another kind of problem, I got notifications on BOTH watch and iPhone, unlike the previous when you only got notifications on Watch if connected. This is weird.

**Comment by eriksmets** [comment]
I think it's due to how userland is (re)loaded. When I modify 'reload' to exit on line 2, AppleWatch keeps working fine.  (Obviously breaks Substrate)

**Comment by keldegar** [comment]
So after charging my re-paired watch overnight, this morning I was not able to receive notifications at all. DND mirroring did not work. However this time after I put my phone into airplane mode, I was able to mirror dnd after that.

**Comment by andrei085** [comment]
The issues with Apple Watch are fixed in the latest version?

**Comment by nullpixel1** [comment]
Should be!

**Comment by cyanisaac** [comment]
Still encountering the same issues, running iOS 10.2 with yalu102 beta 2 on my iPhone 6s + Apple Watch Series 2 w/ watchOS 3.1.3.

**Comment by coolstar** [comment]
Tested here with yalu 10.2 commit 731b7a1bf5c5a2ce3f4fb119829af6c3f3425021 on a freshly restored iPhone 6.

I removed the mount() call so that yalu 10.2 only applies patches and doesn't reload the userland or extract the bootstrap tar.

Can confirm that the issue is not in the jailbreak itself, but with how the userland is reloaded or how the tar is extracted. Notifications are arriving on my Apple Watch (watchOS 3.1.3) only 0.75 seconds after the phone, so it's fair to say it's working correctly

**Comment by eriksmets** [comment]
The error is not in bootstrap.tar, as just modifying the reload command works. 
(Also, after a reboot but before running yalu102, everything works fine, and the device is already bootstrapped then)

**Comment by andrei085** [comment]
@coolstar where is the mount() call? in jailbreak.m at //mount patch? I already have bootstrap extracted

**Comment by coolstar** [comment]
@eriksmets cool, I'll give that a try here and check

**Comment by kpwn** [comment]
fixed the issue in latest commit

**Comment by keldegar** [comment]
Thank you!
