### ISSUE TITLE
Spinning wheel while rejailbreaking

### ISSUE THREAD

**Issue by Vetalius** [kpwn/yalu102#329]
Jailbreaked my iPhone 6 10.2 with Yalu's solution. Did not install any of the forbidden tweaks like AppSync etc. And now after reboot when i try to rejailbreak when the device resprings i receive a spinning wheel which does not finish the process.

**Comment by Vetalius** [comment]
https://youtu.be/g_7s_pMaZFA
Here is a video of a similar problem.

**Comment by kpwn** [comment]
Does ssh work? You can edit the reload script to only load ssh and it will not be an issue.

This is puzzling me however since as-is reload should work.

**Comment by Vetalius** [comment]
I am trying to access the phone via Putty. I enter iPhones wi-fi IP and it says that connection refused, maybe i am doing something wrong because i have never done that before.

**Comment by kpwn** [comment]
You need to use SSH over USB with Yalu. 

Just google 'ssh over usb ios'

**Comment by Vetalius** [comment]
![capture](https://cloud.githubusercontent.com/assets/25454558/22462443/fc199fb0-e7b5-11e6-942f-321d9d19e223.PNG)
Here is what i get.

**Comment by kpwn** [comment]
That means SSH is not running. You should edit the 'reload' file to only do:

<pre>
launchctl load /Library/LaunchDaemons/dropbear.plist
</pre>


You can then debug what's happened more properly.

**Comment by OGKevin** [comment]
https://www.reddit.com/r/jailbreak/comments/5r2mwr/tutorial_how_to_use_dropbear_ssh_via_usb_on/?st=IYLF5ZZA&sh=ca9f681f

**Comment by 0neday** [comment]
Edit jailbreak.m in source code and only load dropbear.plist, login system using it, and rm /.installed_yaluX and reboot,  then rejailbreak, that maybe fix  your issues, good luck

**Comment by Vetalius** [comment]
I am not good in debugging and that sort of stuff, so please, if you can lay the instruction in more simple terms. Thank you =).

**Comment by Vetalius** [comment]
Tunneling via iFunbox does not work.

**Comment by Vetalius** [comment]
What do I use to edit the yalu.ipa?

**Comment by maetrik92** [comment]
@Vetalius you need Xcode to edit and compile.if you are not experienced why did you go ahead on a beta of Yalu?

**Comment by OGKevin** [comment]
U made @kpwn aware of this issues but if your not good in debugging and stuff like that then i suggest u wait for stable. Unless he is willing and has the time to explain it in "baby steps" for you. Maybe someone more advanced can recreate this issue and provide better info.

**Comment by Vetalius** [comment]
The issue might be tied to Power Tap or Anemone tweaks.

**Comment by Vetalius** [comment]
I must also note that removing the Yalu app on the phone and then reinjecting the .ipa via Impactor does not improve the issue.

**Comment by kpwn** [comment]
ipa files are zip files. extract it, there's a file called reload inside it, open it with notepad++, comment everything but the '#!/bin/sh' line out (commenting is done by adding a # at the beginning of the line), then adding the launchctl command I wrote earlier to it. Compress the 'Payload' folder back to a zip and install it with Impactor.

**Comment by jde1126** [comment]
I myself am having this exact issue! 

I had not  experienced it, until I tried installing many tweaks last night.

 Fortunately, I have a mac with XCode, and can debug.

I just got off work, I will comment back in hopefully an hour, for reference, these are the tweaks that I installed with the error. (List is pretty much useless if it is because of a collision with the others I had.)

Facebook++
YouTube++
Infinity Task (iOS 9)
MessagePopper
Message Loaded
PM, Really?
Safe Alarm 2 (iOS 9+)
361 *Chinese Letters* (MultiAccountMaster)

Also note, I have been using "Illigal Sources", because cydia was not allowing me to log into my Facebook account, to access previous purchases. (The Cydia Beta repo fixed that though.)

**Comment by jde1126** [comment]
So after spending a while trying to SSH into my iPhone, I gave up.
Error: (Connection closed by host.)

I however found (a link to) THE [solution](https://www.reddit.com/r/jailbreak/comments/5r8wi4/tutorial_enter_substrate_safe_mode_ios_10_yalu/)! 

After booting with No Substrate,
I uninstalled my previous tweaks, 
Restarted Springboard, 
*POWERED OFF DEVICE*, (Upon restarting, you will still be in No Substrate mode)
(Powered back On)
then opened yalu102, 
And after clicking "go", it showed the scary loading circle for a little,
But then booted normal!!  

**Jailbreak works as should.**
**I would rule this issue as Closed, and not a problem with the Jailbreak!**

(I hope this helps Vetalius)

Additional Information:
-I am on an iPhone 6s+
-10.2
-Using yalu102 with most recent commit. (Therefore Obviously MacOS)
(Above information probably irrelevant)

**Comment by zachal** [comment]
#162 
Had the same problem, not an issue with the jailbreak, was an issue with installed tweaks.

To fix: 
1. comment out the line:
system("(echo 'really jailbroken'; /bin/launchctl load /Library/LaunchDaemons/0.reload.plist)&");
2. run jailbreak,
3. open cydia, delete all tweaks
4. reboot
5. uncomment line and rerun jailbreak

**Comment by WhatsInYourWall** [comment]
This happened to me until I found a glorious Reddit post. Although it's not there anymore, the gist was that the reload script was not working. Regardless if I had installed any incompatible tweaks or not, I never had a problem once jailbroken and all my tweaks are on the compatible page. The way that I circumvented the problem was by taking the def.plist from mach_portal beta 4 (that jailbreak worked like butter, props kpwn) and replacing the beta(insert #) 0.reload.plist with it and then just renaming it 0.reload.plist. Granted that after the jailbreak I had Cydia and everything but it would not respring it would just show "already jailbroken" and this works flawlessly everytime so far. It's just that I have to run "/etc/rc.d/substrate" and "killall SpringBoard" everytime after to load Cydia Substrate. Hopefully this insight can help anyone in that respring problem while allowing them to keep their tweaks.

**Comment by Vetalius** [comment]
Issue solved by holding volume up + power when pressing GO in Yalu app and holding those buttons until the lockscreen appears. Thank you everyone for help.

**Comment by ErikHumphrey** [comment]
Still having this issue. Is the volume up + power combo different per device?

**Comment by Vetalius** [comment]
I don't think so. Should be the same. But I already updated to newer iOS
firmware, so no Yalu jailbreak for me.

**Comment by OGKevin** [comment]
This project is also discontinued so 🤷‍♂️

**Comment by ErikHumphrey** [comment]
@Vetalius Managed to fix it thanks to the no substrate solution, but thanks

**Comment by EfosaSO** [comment]
For those who experience this issue again and don't want to go through all; those steps, there's a simpler method:

after you tap go, hold volume up. When the screen comes on, remove whatever tweak may be not working. then reboot. Enjoy

[Source](https://www.reddit.com/r/jailbreak/comments/5vtbzn/question_iphone_6_stuck_on_spinning_wheel_after/)
