### ISSUE TITLE
IOS 10.2 I6 reboots/ Crashes

### ISSUE THREAD

**Issue by DontAskMeIt** [kpwn/yalu102#343]
I Don't know if this is an issue or a bug, Just wanted to let you know even on beta 7 I am getting this random crash. 
I read the issue posting guidelines.

**Comment by DontAskMeIt** [comment]
At random times in the jailbroken state it just reboots.

**Comment by jitterbvg** [comment]
I'm having this problem as well except my Cydia crashes when a tweak is finishing downloading.

**Comment by bobbysn0w** [comment]
@jitterbvg Should be a new repo and update for Cydia. (Round 3 of the Cydia betas) that fixes that problem. Go to /r/Jailbreak's front page somewhere to find it.

**Comment by tangalbert919** [comment]
Here's the repo: http://apt.saurik.com/beta/cydia-arm64/
This is just odd, considering my phone is doing just fine on beta 7 (not even joking). And it's an iPhone 6.

**Comment by jitterbvg** [comment]
does that repo fix the issue? or ? and the beta 3 link download isnt working anymore

**Comment by tangalbert919** [comment]
The repo does not necessary "fix" the whole restart thing, but it will make Cydia less buggy, despite it being in beta right now (1.1.28~b9 at the time of this comment).
Just keep using beta 7 of the Yalu jailbreak. Honestly, that's all we have.

**Comment by jitterbvg** [comment]
thanks! it actually worked, no more crashing

**Comment by XeNoW** [comment]
I'm having similar problems on the iPhone 6, iOS 10.2:
- The jailbreak process sometimes fails on the first attempt after a reboot and restarts the device in a non-jailbroken mode (JB apps do not start). Sometimes the second attempt works, sometimes another manual reboot is required before it works again.
- Sometimes I have random freezes of the device (e.g. while navigting on homescreen). A hard reboot is required afterwards.
- May not be JB related: Substrate Safe Mode automatically restarts springboard after unlock. Afterwards the device is in a state where mobile substrate, PreferenceLoader etc. is not loaded at all. However, jailbreak apps can be started and complain about missing MobileSubstrate/RocketBootstrap. Only a respring (e.g. initiated over the Activator app) returns the device in the proper jailbroken state.
- Yesterday it showed me a message stating that my SIM Card was not found. However, the phone unlocked without problems... Could be unrelated.

**Comment by AbouImran** [comment]
Cydia64_1.1.28~b9 = less problems

**Comment by JMccormick264** [comment]
the latest cydia beta fixed the crashes for me so far. I just installed the latest maybe 8 hours ago. haven't had a crash

**Comment by XeNoW** [comment]
Alrwady have the latest Cydia version. Will keep note if it fixed the issues.

**Comment by XeNoW** [comment]
Springboard just randomly crashed while using the Youtube app (no associated tweaks installed) and afterwards was again in this jailbroken mode without mobile substrate and without safe mode. A respring got my device to stuck at a black screen without spinning wheele. I had to do a hard reset to restart the phone.

**Comment by XeNoW** [comment]
Just had this again: "The jailbreak process sometimes fails on the first attempt after a reboot and restarts the device in a non-jailbroken mode (JB apps do not start). Sometimes the second attempt works, sometimes another manual reboot is required before it works again."

So: No, the new Cydia did not fix the problem.

**Comment by XeNoW** [comment]
Ok even a restart did nit directly fix this and the jailbreak did only work on the second attempt. There are indeed some hick-ups in the JB process.

**Comment by DontAskMeIt** [comment]
Il check if there is an update, Do I have to update the Yalu app?

**Comment by DontAskMeIt** [comment]
I'm on beta 9... still crashes occur

**Comment by iOSJesusDev** [comment]
Wtf beta 9? That's not possible. Are you talking about Cydia?

**Comment by kpwn** [comment]
send logs next time

**Comment by XeNoW** [comment]
![img_6070](https://cloud.githubusercontent.com/assets/29659/22522446/db95558e-e8bb-11e6-813c-28a52dcb53bd.PNG)
![img_6073](https://cloud.githubusercontent.com/assets/29659/22522447/db9777e2-e8bb-11e6-9d14-5056c7c8a51f.PNG)

**Comment by XeNoW** [comment]
Here you go. Random panic while doing nothing special...
SCREENSHOTS REMOVED

**Comment by XeNoW** [comment]
![img_6070](https://cloud.githubusercontent.com/assets/29659/22522540/30a9e80a-e8bc-11e6-8ea9-ca883b8687f6.PNG)
![img_6073](https://cloud.githubusercontent.com/assets/29659/22522542/30c9128e-e8bc-11e6-89c9-f26e13697fe8.PNG)

**Comment by egamer24** [comment]
Have you updated safe mode yet?

**Comment by XeNoW** [comment]
Just now. From the changelog it seems that the safe mode problem was fixed:
"(In specific, the expected dialog now appears, but if you are using the older Yalu for 10.0-10.1.1 jailbreaks, including the final "b3", clicking Restart will cause the device to lock up so you will need to reboot. This continues to be a known issue with this jailbreak.)"

As i'm not on b3 this should not explain the lock ups / freezes.

Also the panic should not be related to this. Here another fresh ome that happened while looking at pictures in the photo app and one from yesterday:
![img_0916](https://cloud.githubusercontent.com/assets/29659/22523715/a080c05a-e8c0-11e6-97a8-724881ae6f7b.JPG)
![img_6075](https://cloud.githubusercontent.com/assets/29659/22523714/a05d4c88-e8c0-11e6-97b7-c7683a0b8ce2.PNG)

**Comment by XeNoW** [comment]
Just now. From the changelog it seems that the safe mode problem was fixed:
"(In specific, the expected dialog now appears, but if you are using the older Yalu for 10.0-10.1.1 jailbreaks, including the final "b3", clicking Restart will cause the device to lock up so you will need to reboot. This continues to be a known issue with this jailbreak.)"

Anyway, as i'm not on b3 this should not explain the lock ups / freezes.

Also the panic should not be related to this.

SCREENSHOTS REMOVED

**Comment by DontAskMeIt** [comment]
Updated cydia to beta 9 and it still is happening, not as much but still happening, yes I also updated substrate safe mode

**Comment by DontAskMeIt** [comment]
I looked at some logs and it says a lot of springboard loops with UIKit

**Comment by sanjubaby** [comment]
Hi i was using 10.2 yalu jailbreak and succesfully jailbroked
but today after reboot on winterboard installation 

am unable to open yaly102
it keep crashing, please help

**Comment by KILLCAMPER** [comment]
@sanjubaby re install Yalu beta 7 0n your pad a Weill have to every 7 days

**Comment by miztizm** [comment]
Yalu beta 7 random reboots here. After 2 days of use

**Comment by KILLCAMPER** [comment]
What device crash log ? And would say tweeks  will be problem remove resent tweeks as lot are not updated to ios10
